JDP191201-48
interceptor2048/project-jdp-1912-01 pull request #34
Opened 2020-01-19 11:31 UTC by radoslaw-lazur

2020-01-20 11:40 UTC, PawelM-code requested changes
Kilka rzeczy:
 - W CartDto pola powinny być Dto, omyłkowo dodałem kiedyś domain, powinn być :

    private List<ProductDto> products = new ArrayList<>();
    private UserDto userDto;

- moja propozycje zmian w komentarzach

w związku z proponowanymi zmianami dodać też należało w ProductMapper:

    public List<Product> mapToProductList(final List<ProductDto> productList) {
        return productList.stream()
                .map(p -> new Product(
                        p.getProductName(),
                        p.getProductType(),
                        groupMapper.mapToGroup(p.getGroupDto())))
                .collect(Collectors.toList());
    }

2020-01-20 11:40 UTC, PawelM-code commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
>  import com.kodilla.ecommercee.domain.dto.CartDto;
do usunięcia nieużywane importy

2020-01-20 11:40 UTC, PawelM-code commented on src/main/java/com/kodilla/ecommercee/mapper/CartMapper.java
> +    }
public Cart mapToCart(final CartDto cartDto) {
        return new Cart(cartDto.getId(),
                        productMapper.mapToProductList(cartDto.getProducts()),
                        userService.getUser(cartDto.getUserDto().getId()).orElseThrow(UserNotFoundException::new));
    }

2020-01-20 11:40 UTC, PawelM-code commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        dbCartService.getCart(cartId).getProducts().remove(dbProductService.getProduct(productId));
dbCartService.removeProductFromCart(cartId,productId);

2020-01-20 11:40 UTC, PawelM-code commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        dbCartService.getCart(cartId).getProducts().add(dbProductService.getProduct(productId));
dbCartService.addProductToCart(cartId,productId);

2020-01-20 11:40 UTC, PawelM-code commented on src/main/java/com/kodilla/ecommercee/mapper/CartMapper.java
> +public class CartMapper {
nieużywane metody bym usunął

2020-01-20 11:40 UTC, PawelM-code commented on src/main/java/com/kodilla/ecommercee/service/DbCartService.java
> +    }
w związku z proponowanymi zmianami dodałem:

    public Cart addProductToCart(final Long cartId, final Long productId){
        Cart cartToAddProduct = cartRepository.findById(cartId).orElseThrow(CartNotFoundException::new);
        cartToAddProduct.getProducts().add(productRepository.findById(productId).orElseThrow(ProductNotFoundException::new));
        return cartRepository.save(cartToAddProduct);
    }

    public Cart removeProductFromCart(final Long cartId, final Long productId){
        Cart cartToAddProduct = cartRepository.findById(cartId).orElseThrow(CartNotFoundException::new);
        cartToAddProduct.getProducts().remove(productRepository.findById(productId).orElseThrow(ProductNotFoundException::new));
        return cartRepository.save(cartToAddProduct);
    }

2020-01-20 11:40 UTC, PawelM-code commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
>      private User user;
dodałbym poniższą adnotację lepiej to wygląda na bazie (hibernate tworzy user_user_id)

@JoinColumn(name = "user_id")

2020-01-21 18:57 UTC, PawelM-code approved these changes

2020-01-21 21:22 UTC, Sephirot92 approved these changes

2020-01-22 06:23 UTC, merged