JDP191201-29
interceptor2048/project-jdp-1912-01 pull request #8
Opened 2019-12-20 22:42 UTC by radoslaw-lazur

Wstępna implementacja OrderController. Dorzuciłem exception do użycia później na wypakowanie z optionala podczas getOrder dla repository Optional<Order> findById(Long id);

2019-12-20 23:03 UTC, DariuszKny requested changes

2019-12-20 23:03 UTC, DariuszKny commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +@RequestMapping("/v1/orders")
/v1/order -> do zachowania spójności z productController

2019-12-20 23:03 UTC, DariuszKny commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public OrderDto updateOrder(@RequestParam Long orderId) {
Czemu nie (@RequestBody OrderDto orderDto) ?

2019-12-20 23:03 UTC, DariuszKny commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public void createOrder(@RequestParam OrderDto orderDto) {
j.w

2019-12-20 23:12 UTC, radoslaw-lazur commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public void createOrder(@RequestParam OrderDto orderDto) {
Masz rację,  zrobiłem update poniżej. Dzięki za czujność.

2019-12-20 23:15 UTC, DariuszKny approved these changes

2019-12-21 05:36 UTC, PawelM-code approved these changes

2019-12-21 09:00 UTC, MichalOrlowski commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    public OrderDto getOrder(@RequestParam Long orderId) throws OrderNotFoundException {
to Unchecked exception, więc niepotrzebne jest "throws"

2019-12-21 19:39 UTC, interceptor2048 approved these changes

2019-12-21 19:50 UTC, merged